# Generated by Django 5.2.7 on 2026-02-09 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_music', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('last_classified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube Channel',
                'verbose_name_plural': 'YouTube Channels',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('LISTEN', 'Listen'), ('LIKE', 'Like'), ('PLAYLIST', 'Playlist add')], default='LISTEN', max_length=20)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='SpotifyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlists_etag', models.TextField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('tracks_etag', models.CharField(blank=True, max_length=128, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_collaborative', models.BooleanField(default=False)),
                ('tracks_count', models.IntegerField(default=0)),
                ('owner_spotify_id', models.CharField(max_length=100)),
                ('owner_display_name', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_id', models.CharField(blank=True, max_length=100)),
                ('tracks_snapshot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spotify Playlist',
                'verbose_name_plural': 'Spotify Playlists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SpotifyPlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='users.spotifyplaylist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='music.track')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['playlist'], name='users_spoti_playlis_64424c_idx'), models.Index(fields=['track'], name='users_spoti_track_i_b3f2d1_idx')],
                'unique_together': {('playlist', 'track')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_started_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_quality', models.CharField(blank=True, choices=[('GOOD', 'Enough signal'), ('LOW', 'Weak signal')], max_length=20, null=True)),
                ('onboarding_likes_count', models.PositiveIntegerField(default=0)),
                ('onboarding_swipes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['onboarding_completed'], name='users_userp_onboard_86dd20_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('artist', 'Artist'), ('track', 'Track')], max_length=20)),
                ('time_range', models.CharField(choices=[('short_term', 'Last 4 weeks'), ('medium_term', 'Last 6 months'), ('long_term', 'All time')], max_length=20)),
                ('rank', models.PositiveIntegerField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('artist__isnull', False), ('track__isnull', True)), models.Q(('artist__isnull', True), ('track__isnull', False)), _connector='OR'), name='either_artist_or_track'), models.CheckConstraint(condition=models.Q(models.Q(('artist__isnull', False), ('item_type', 'artist'), ('track__isnull', True)), models.Q(('artist__isnull', True), ('item_type', 'track'), ('track__isnull', False)), _connector='OR'), name='item_type_matches_object')],
                'unique_together': {('user', 'item_type', 'time_range', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='YoutubeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('subscriptions_etag', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'YouTube Account',
                'verbose_name_plural': 'YouTube Accounts',
                'indexes': [models.Index(fields=['expires_at'], name='users_youtu_expires_f0e166_idx'), models.Index(fields=['last_synced_at'], name='users_youtu_last_sy_4eefa6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserYoutubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='users.youtubechannel')),
            ],
            options={
                'verbose_name': 'User YouTube Channel',
                'verbose_name_plural': 'User YouTube Channels',
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_usery_user_id_f6d023_idx'), models.Index(fields=['channel', 'notifications_enabled'], name='users_usery_channel_bdfd12_idx')],
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
