# Generated by Django 5.1.15 on 2026-04-01 15:56

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyaccount',
            name='access_token',
            field=users.models.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='refresh_token',
            field=users.models.EncryptedTextField(),
        ),
    ]
