# Generated by Django 5.2.7 on 2025-11-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_spotifyaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField(null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('genres', models.ManyToManyField(related_name='artists', to='users.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('duration_ms', models.IntegerField()),
                ('popularity', models.IntegerField(null=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('artists', models.ManyToManyField(related_name='tracks', to='users.artist')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.track')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('artist', 'Artist'), ('track', 'Track')], max_length=255)),
                ('time_range', models.CharField(choices=[('short_term', 'Last 4 weeks'), ('medium_term', 'Last 6 months'), ('long_term', 'All time')], max_length=20)),
                ('rank', models.IntegerField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
