# Generated by Django 5.2.7 on 2025-11-02 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_genre_artist_track_listeninghistory_usertopitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertopitem',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.artist'),
        ),
        migrations.AlterField(
            model_name='usertopitem',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.track'),
        ),
    ]
