# Generated by Django 5.2.7 on 2025-11-15 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usertopitem_artist_alter_usertopitem_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertopitem',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artist'),
        ),
        migrations.AlterField(
            model_name='usertopitem',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.track'),
        ),
    ]
