# Generated by Django 5.2.7 on 2025-11-16 18:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usertopitem_artist_alter_usertopitem_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danceability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('energy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('valence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('acousticness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('instrumentalness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('speechiness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('liveness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('loudness', models.FloatField(validators=[django.core.validators.MinValueValidator(-60.0), django.core.validators.MaxValueValidator(0.0)])),
                ('key', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(11)])),
                ('mode', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('tempo', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('time_signature', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)])),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_features', to='users.track')),
            ],
            options={
                'verbose_name_plural': 'Audio Features',
            },
        ),
    ]
