# Generated by Django 5.2.7 on 2025-12-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_youtubeaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubeaccount',
            old_name='expires_in',
            new_name='expires_at',
        ),
        migrations.AddField(
            model_name='youtubeaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
