# Generated by Django 5.2.7 on 2025-12-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_expires_in_youtubeaccount_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubeaccount',
            options={'verbose_name': 'YouTube Account', 'verbose_name_plural': 'YouTube Accounts'},
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='event_type',
            field=models.CharField(choices=[('LISTEN', 'Listen'), ('LIKE', 'Like'), ('PLAYLIST', 'Playlist add')], default='LISTEN', max_length=20),
        ),
    ]
