# Generated by Django 5.2.7 on 2026-01-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_album_alter_track_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertopitem',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.artist'),
        ),
        migrations.AlterField(
            model_name='usertopitem',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.track'),
        ),
    ]
