# Generated by Django 5.2.7 on 2026-01-06 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_album_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_collaborative', models.BooleanField(default=False)),
                ('tracks_count', models.IntegerField(default=0)),
                ('owner_spotify_id', models.CharField(max_length=100)),
                ('owner_display_name', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spotify Playlist',
                'verbose_name_plural': 'Spotify Playlists',
                'ordering': ['-updated_at'],
            },
        ),
    ]
