# Generated by Django 5.2.7 on 2026-01-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_spotifyplaylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyPlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='users.spotifyplaylist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='users.track')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['playlist'], name='users_spoti_playlis_64424c_idx'), models.Index(fields=['track'], name='users_spoti_track_i_b3f2d1_idx')],
                'unique_together': {('playlist', 'track')},
            },
        ),
    ]
