# Generated by Django 5.2.7 on 2026-01-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_spotifyplaylisttrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyplaylist',
            name='tracks_snapshot_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
