# Generated by Django 5.2.7 on 2026-01-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_spotifyplaylist_tracks_snapshot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyplaylist',
            name='etag',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='spotifyplaylist',
            name='tracks_etag',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
