# Generated by Django 5.2.7 on 2026-01-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_spotifyplaylist_etag_spotifyplaylist_tracks_etag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyplaylist',
            name='etag',
        ),
        migrations.AddField(
            model_name='spotifyaccount',
            name='playlists_etag',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
