# Generated by Django 5.2.7 on 2026-01-11 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_spotifyplaylist_etag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserYouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User YouTube Channel',
                'verbose_name_plural': 'User YouTube Channels',
            },
        ),
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_music', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('last_classified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube Channel',
                'verbose_name_plural': 'YouTube Channels',
            },
        ),
        migrations.AddField(
            model_name='youtubeaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubeaccount',
            name='subscriptions_etag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='youtubeaccount',
            index=models.Index(fields=['expires_at'], name='users_youtu_expires_f0e166_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubeaccount',
            index=models.Index(fields=['last_synced_at'], name='users_youtu_last_sy_4eefa6_idx'),
        ),
        migrations.AddField(
            model_name='useryoutubechannel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useryoutubechannel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.youtubechannel'),
        ),
        migrations.AlterUniqueTogether(
            name='useryoutubechannel',
            unique_together={('user', 'channel')},
        ),
    ]
