# Generated by Django 5.2.7 on 2026-01-18 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_useryoutubechannel_youtubechannel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='album_name',
            new_name='album',
        ),
        migrations.AddField(
            model_name='useryoutubechannel',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useryoutubechannel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='users.youtubechannel'),
        ),
        migrations.AlterField(
            model_name='useryoutubechannel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useryoutubechannel',
            index=models.Index(fields=['user', 'created_at'], name='users_usery_user_id_f6d023_idx'),
        ),
        migrations.AddIndex(
            model_name='useryoutubechannel',
            index=models.Index(fields=['channel', 'notifications_enabled'], name='users_usery_channel_bdfd12_idx'),
        ),
    ]
