# Generated by Django 5.2.7 on 2026-01-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_album_name_track_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
