# Generated by Django 5.2.7 on 2026-01-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_spotifyaccount_last_synced_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeaccount',
            name='youtube_id',
        ),
    ]
