# Generated by Django 5.2.7 on 2026-01-23 16:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_youtubeaccount_youtube_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('genre', 'Genre'), ('mood', 'Mood'), ('instrument', 'Instrument'), ('era', 'Era'), ('style', 'Style'), ('theme', 'Theme'), ('other', 'Other')], default='other', max_length=50)),
                ('total_usage_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_usage_count', 'name'],
                'indexes': [models.Index(fields=['normalized_name'], name='users_tag_normali_6fc33e_idx'), models.Index(fields=['category', 'normalized_name'], name='users_tag_categor_655f87_idx'), models.Index(fields=['category', '-total_usage_count'], name='users_tag_categor_ce3c8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArtistLastFMData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastfm_name', models.CharField(max_length=255)),
                ('lastfm_url', models.URLField(blank=True, null=True)),
                ('mbid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('listeners', models.BigIntegerField(blank=True, null=True)),
                ('playcount', models.BigIntegerField(blank=True, null=True)),
                ('raw_tags', models.JSONField(blank=True, default=list)),
                ('bio_summary', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('match_confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lastfm_cache', to='users.artist')),
            ],
            options={
                'db_table': 'lastfm_artist_cache',
                'indexes': [models.Index(fields=['fetched_at'], name='lastfm_arti_fetched_4056c4_idx'), models.Index(fields=['playcount'], name='lastfm_arti_playcou_8b4bc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArtistTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(default='lastfm', max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_tags', to='users.artist')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_artists', to='users.tag')),
            ],
            options={
                'ordering': ['-weight'],
                'indexes': [models.Index(fields=['artist', '-weight'], name='users_artis_artist__403683_idx')],
                'unique_together': {('artist', 'tag', 'source')},
            },
        ),
        migrations.CreateModel(
            name='TrackLastFMData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastfm_name', models.CharField(max_length=255)),
                ('lastfm_artist_name', models.CharField(max_length=255)),
                ('lastfm_url', models.URLField(blank=True, null=True)),
                ('mbid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('listeners', models.BigIntegerField(blank=True, null=True)),
                ('playcount', models.BigIntegerField(blank=True, null=True)),
                ('raw_tags', models.JSONField(blank=True, default=list)),
                ('match_confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lastfm_cache', to='users.track')),
            ],
            options={
                'db_table': 'lastfm_track_cache',
                'indexes': [models.Index(fields=['fetched_at'], name='lastfm_trac_fetched_1a704d_idx'), models.Index(fields=['playcount'], name='lastfm_trac_playcou_199d47_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(default='lastfm', max_length=20)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_tracks', to='users.tag')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_tags', to='users.track')),
            ],
            options={
                'ordering': ['-weight'],
                'indexes': [models.Index(fields=['track', '-weight'], name='users_track_track_i_63b3bf_idx')],
                'unique_together': {('track', 'tag', 'source')},
            },
        ),
    ]
