# Generated by Django 5.2.7 on 2026-01-23 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_tag_artistlastfmdata_artisttag_tracklastfmdata_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracktag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tracktag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tracktag',
            name='track',
        ),
        migrations.AddField(
            model_name='artisttag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisttag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artisttag',
            name='raw_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artisttag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artisttag',
            name='source',
            field=models.CharField(choices=[('lastfm', 'Last.fm raw'), ('spotify', 'Spotify genres'), ('computed', 'Computed canonical'), ('manual', 'Manual')], default='lastfm', max_length=20),
        ),
        migrations.AddIndex(
            model_name='artisttag',
            index=models.Index(fields=['tag', '-weight'], name='users_artis_tag_id_7e64f3_idx'),
        ),
        migrations.AddIndex(
            model_name='artisttag',
            index=models.Index(fields=['source'], name='users_artis_source_9266de_idx'),
        ),
        migrations.DeleteModel(
            name='TrackTag',
        ),
    ]
