# Generated by Django 5.2.7 on 2026-01-23 17:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_tracktag_unique_together_remove_tracktag_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(choices=[('lastfm', 'Last.fm raw'), ('audio', 'Audio features'), ('artist', 'Inherited from artist'), ('computed', 'Computed canonical'), ('manual', 'Manual')], default='lastfm', max_length=20)),
                ('raw_count', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_tracks', to='users.tag')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_tags', to='users.track')),
            ],
            options={
                'ordering': ['-weight'],
                'indexes': [models.Index(fields=['track', '-weight'], name='users_track_track_i_63b3bf_idx'), models.Index(fields=['tag', '-weight'], name='users_track_tag_id_85cbc0_idx'), models.Index(fields=['source'], name='users_track_source_d2b2bf_idx')],
                'unique_together': {('track', 'tag', 'source')},
            },
        ),
    ]
