# Generated by Django 5.2.7 on 2026-01-24 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_tag_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(choices=[('lastfm', 'Last.fm'), ('tags', 'Tag-based'), ('audio', 'Audio-based'), ('hybrid', 'Hybrid')], default='tags', max_length=20)),
                ('score_breakdown', models.JSONField(blank=True, help_text='Explainability data, e.g. {"tag_sim": 0.7, "audio_sim": 0.5}', null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='users.artist')),
                ('to_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='users.artist')),
            ],
            options={
                'verbose_name': 'Artist Similarity',
                'verbose_name_plural': 'Artist Similarities',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['from_artist', 'source', '-score'], name='users_artis_from_ar_6991bf_idx'), models.Index(fields=['to_artist', '-score'], name='users_artis_to_arti_d04e3c_idx')],
                'unique_together': {('from_artist', 'to_artist', 'source')},
            },
        ),
        migrations.CreateModel(
            name='TrackSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(choices=[('lastfm', 'Last.fm'), ('tags', 'Tag-based'), ('audio', 'Audio-based'), ('hybrid', 'Hybrid')], default='tags', max_length=20)),
                ('score_breakdown', models.JSONField(blank=True, help_text='Explainability data, e.g. {"tag_sim": 0.7, "audio_sim": 0.5}', null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='users.track')),
                ('to_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='users.track')),
            ],
            options={
                'verbose_name': 'Track Similarity',
                'verbose_name_plural': 'Track Similarities',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['from_track', 'source', '-score'], name='users_track_from_tr_3d51c7_idx'), models.Index(fields=['to_track', '-score'], name='users_track_to_trac_755943_idx')],
                'unique_together': {('from_track', 'to_track', 'source')},
            },
        ),
    ]
