# Generated by Django 5.2.7 on 2026-01-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_artistsimilarity_tracksimilarity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertopitem',
            options={'ordering': ['rank']},
        ),
        migrations.AlterField(
            model_name='usertopitem',
            name='item_type',
            field=models.CharField(choices=[('artist', 'Artist'), ('track', 'Track')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usertopitem',
            name='rank',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='usertopitem',
            unique_together={('user', 'item_type', 'time_range', 'rank')},
        ),
        migrations.AddConstraint(
            model_name='usertopitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artist__isnull', False), ('track__isnull', True)), models.Q(('artist__isnull', True), ('track__isnull', False)), _connector='OR'), name='either_artist_or_track'),
        ),
        migrations.AddConstraint(
            model_name='usertopitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artist__isnull', False), ('item_type', 'artist'), ('track__isnull', True)), models.Q(('artist__isnull', True), ('item_type', 'track'), ('track__isnull', False)), _connector='OR'), name='item_type_matches_object'),
        ),
    ]
