# Generated by Django 5.2.7 on 2026-02-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_usertopitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='preview_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('embed', 'Embed')], default='embed', max_length=10),
        ),
        migrations.AlterField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
