# Generated by Django 5.2.7 on 2026-02-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_album_spotify_id_alter_artist_spotify_id_and_more'),
        ('users', '0028_track_preview_type_alter_album_spotify_id_and_more'),
    ]

    operations = [
    ]
