# Generated by Django 5.2.7 on 2026-02-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_merge_20260202_2153'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(condition=models.Q(('spotify_id__isnull', False)), fields=('spotify_id',), name='unique_spotify_id_not_null'),
        ),
    ]
