# Generated by Django 5.2.7 on 2026-02-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_quality',
            field=models.CharField(blank=True, choices=[('GOOD', 'Enough signal'), ('LOW', 'Weak signal')], max_length=20, null=True),
        ),
    ]
