# Generated by Django 5.2.7 on 2026-02-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_userprofile_onboarding_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyaccount',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='playlists_etag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='refresh_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='youtubeaccount',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='youtubeaccount',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
