# Generated by Django 5.2.7 on 2026-02-09 22:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField(null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('album_type', models.CharField(choices=[('album', 'Album'), ('single', 'Single'), ('compilation', 'Compilation')], default='album', max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artists', models.ManyToManyField(related_name='albums', to='music.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(related_name='artists', to='music.genre'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('genre', 'Genre'), ('mood', 'Mood'), ('instrument', 'Instrument'), ('era', 'Era'), ('style', 'Style'), ('theme', 'Theme'), ('other', 'Other')], default='other', max_length=50)),
                ('total_usage_count', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_usage_count', 'name'],
                'indexes': [models.Index(fields=['normalized_name'], name='music_tag_normali_b85c83_idx'), models.Index(fields=['category', 'normalized_name'], name='music_tag_categor_60415c_idx'), models.Index(fields=['category', '-total_usage_count'], name='music_tag_categor_337667_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArtistTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(choices=[('lastfm', 'Last.fm raw'), ('spotify', 'Spotify genres'), ('computed', 'Computed canonical'), ('manual', 'Manual')], default='lastfm', max_length=20)),
                ('raw_count', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_tags', to='music.artist')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_artists', to='music.tag')),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('duration_ms', models.IntegerField()),
                ('popularity', models.IntegerField(null=True)),
                ('preview_type', models.CharField(choices=[('audio', 'Audio'), ('embed', 'Embed')], default='embed', max_length=10)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album')),
                ('artists', models.ManyToManyField(related_name='tracks', to='music.artist')),
            ],
        ),
        migrations.CreateModel(
            name='TrackLastFMData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastfm_name', models.CharField(max_length=255)),
                ('lastfm_artist_name', models.CharField(max_length=255)),
                ('lastfm_url', models.URLField(blank=True, null=True)),
                ('mbid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('listeners', models.BigIntegerField(blank=True, null=True)),
                ('playcount', models.BigIntegerField(blank=True, null=True)),
                ('raw_tags', models.JSONField(blank=True, default=list)),
                ('match_confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lastfm_cache', to='music.track')),
            ],
            options={
                'db_table': 'lastfm_track_cache',
            },
        ),
        migrations.CreateModel(
            name='TrackSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(choices=[('lastfm', 'Last.fm'), ('tags', 'Tag-based'), ('audio', 'Audio-based'), ('hybrid', 'Hybrid')], default='tags', max_length=20)),
                ('score_breakdown', models.JSONField(blank=True, help_text='Explainability data, e.g. {"tag_sim": 0.7, "audio_sim": 0.5}', null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='music.track')),
                ('to_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='music.track')),
            ],
            options={
                'verbose_name': 'Track Similarity',
                'verbose_name_plural': 'Track Similarities',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='TrackTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(choices=[('lastfm', 'Last.fm raw'), ('audio', 'Audio features'), ('artist', 'Inherited from artist'), ('computed', 'Computed canonical'), ('manual', 'Manual')], default='lastfm', max_length=20)),
                ('raw_count', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_tracks', to='music.tag')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_tags', to='music.track')),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='ArtistLastFMData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastfm_name', models.CharField(max_length=255)),
                ('lastfm_url', models.URLField(blank=True, null=True)),
                ('mbid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('listeners', models.BigIntegerField(blank=True, null=True)),
                ('playcount', models.BigIntegerField(blank=True, null=True)),
                ('raw_tags', models.JSONField(blank=True, default=list)),
                ('bio_summary', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('match_confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lastfm_cache', to='music.artist')),
            ],
            options={
                'db_table': 'lastfm_artist_cache',
                'indexes': [models.Index(fields=['fetched_at'], name='lastfm_arti_fetched_4056c4_idx'), models.Index(fields=['playcount'], name='lastfm_arti_playcou_8b4bc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArtistSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(choices=[('lastfm', 'Last.fm'), ('tags', 'Tag-based'), ('audio', 'Audio-based'), ('hybrid', 'Hybrid')], default='tags', max_length=20)),
                ('score_breakdown', models.JSONField(blank=True, help_text='Explainability data, e.g. {"tag_sim": 0.7, "audio_sim": 0.5}', null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='music.artist')),
                ('to_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='music.artist')),
            ],
            options={
                'verbose_name': 'Artist Similarity',
                'verbose_name_plural': 'Artist Similarities',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['from_artist', 'source', '-score'], name='music_artis_from_ar_bb00ef_idx'), models.Index(fields=['to_artist', '-score'], name='music_artis_to_arti_22049f_idx')],
                'unique_together': {('from_artist', 'to_artist', 'source')},
            },
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(condition=models.Q(('spotify_id__isnull', False)), fields=('spotify_id',), name='unique_spotify_id_not_null'),
        ),
        migrations.AddIndex(
            model_name='artisttag',
            index=models.Index(fields=['artist', '-weight'], name='music_artis_artist__65e72c_idx'),
        ),
        migrations.AddIndex(
            model_name='artisttag',
            index=models.Index(fields=['tag', '-weight'], name='music_artis_tag_id_19ba5c_idx'),
        ),
        migrations.AddIndex(
            model_name='artisttag',
            index=models.Index(fields=['source'], name='music_artis_source_e2e3ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artisttag',
            unique_together={('artist', 'tag', 'source')},
        ),
        migrations.AddIndex(
            model_name='tracklastfmdata',
            index=models.Index(fields=['fetched_at'], name='lastfm_trac_fetched_1a704d_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklastfmdata',
            index=models.Index(fields=['playcount'], name='lastfm_trac_playcou_199d47_idx'),
        ),
        migrations.AddIndex(
            model_name='tracksimilarity',
            index=models.Index(fields=['from_track', 'source', '-score'], name='music_track_from_tr_af0cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='tracksimilarity',
            index=models.Index(fields=['to_track', '-score'], name='music_track_to_trac_966694_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tracksimilarity',
            unique_together={('from_track', 'to_track', 'source')},
        ),
        migrations.AddIndex(
            model_name='tracktag',
            index=models.Index(fields=['track', '-weight'], name='music_track_track_i_bf7702_idx'),
        ),
        migrations.AddIndex(
            model_name='tracktag',
            index=models.Index(fields=['tag', '-weight'], name='music_track_tag_id_a6ccc1_idx'),
        ),
        migrations.AddIndex(
            model_name='tracktag',
            index=models.Index(fields=['source'], name='music_track_source_5dfdb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tracktag',
            unique_together={('track', 'tag', 'source')},
        ),
    ]
