[pytest]
DJANGO_SETTINGS_MODULE = Recommender.settings
python_files = test_*.py
addopts =
    -ra
    -q
    --cov=recomendations
    --cov=music
    --cov=users
    --cov=utils
    --cov-report=term-missing