# Generated by Django 5.2.7 on 2026-02-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRACK', 'track'), ('ARTIST', 'artist')], default='TRACK', max_length=10)),
                ('strategy', models.CharField(choices=[('COLD_START', 'cold-start'), ('WARM_START', 'warm-start'), ('HYBRID_START', 'hybrid-start')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'draft'), ('READY', 'ready')], default='DRAFT', max_length=10)),
                ('context', models.JSONField(blank=True, help_text='Context used to generate recommendation (seed items, params, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
