# Generated by Django 5.2.7 on 2026-02-09 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRACK', 'track'), ('ARTIST', 'artist')], default='TRACK', max_length=10)),
                ('strategy', models.CharField(choices=[('COLD_START', 'cold-start'), ('WARM_START', 'warm-start'), ('HYBRID_START', 'hybrid-start')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'draft'), ('READY', 'ready')], default='DRAFT', max_length=10)),
                ('context', models.JSONField(blank=True, help_text='Context used to generate recommendation (seed items, params, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRACK', 'track'), ('ARTIST', 'artist')], max_length=10)),
                ('score', models.FloatField(help_text='Final recommendation score (0–1)')),
                ('rank', models.PositiveIntegerField(help_text='Position in recommendation list (0 = best)')),
                ('reason', models.JSONField(blank=True, help_text='Why this item was recommended (signals, similarities, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='ColdStartTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SPOTIFY_GLOBAL', 'Spotify Global Top'), ('SPOTIFY_VIRAL', 'Spotify Viral'), ('LASTFM_GLOBAL', 'Last.fm Global Top')], db_index=True, max_length=32)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField(blank=True, help_text='Optional normalized score used for ranking', null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True, help_text='Last time this entry was refreshed from the source')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_start_entries', to='music.track')),
            ],
            options={
                'ordering': ['source', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LIKE', 'Like'), ('SKIP', 'Skip'), ('NOT_MY_STYLE', 'Not My Style')], max_length=20)),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='Order in onboarding flow (1..N)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cold_start_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_events', to='recomendations.coldstarttrack')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
