# Generated by Django 5.2.7 on 2026-02-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0001_initial'),
        ('users', '0028_alter_album_spotify_id_alter_artist_spotify_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRACK', 'track'), ('ARTIST', 'artist')], max_length=10)),
                ('score', models.FloatField(help_text='Final recommendation score (0–1)')),
                ('rank', models.PositiveIntegerField(help_text='Position in recommendation list (0 = best)')),
                ('reason', models.JSONField(blank=True, help_text='Why this item was recommended (signals, similarities, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_items', to='users.artist')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recomendations.recommendation')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_items', to='users.track')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('recommendation', 'artist'), ('recommendation', 'track')},
            },
        ),
    ]
