# Generated by Django 5.2.7 on 2026-02-09 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('recomendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_items', to='music.artist'),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recomendations.recommendation'),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_items', to='music.track'),
        ),
        migrations.AddIndex(
            model_name='coldstarttrack',
            index=models.Index(fields=['source', 'rank'], name='recomendati_source_c4bf9e_idx'),
        ),
        migrations.AddIndex(
            model_name='coldstarttrack',
            index=models.Index(fields=['track'], name='recomendati_track_i_387685_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coldstarttrack',
            unique_together={('track', 'source')},
        ),
        migrations.AddIndex(
            model_name='onboardingevent',
            index=models.Index(fields=['user', 'created_at'], name='recomendati_user_id_8805f1_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingevent',
            index=models.Index(fields=['user', 'action'], name='recomendati_user_id_d61bcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardingevent',
            constraint=models.UniqueConstraint(fields=('user', 'cold_start_track'), name='unique_onboarding_event_per_track'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendationitem',
            unique_together={('recommendation', 'artist'), ('recommendation', 'track')},
        ),
    ]
