# Generated by Django 5.2.7 on 2026-02-02 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0002_recommendationitem'),
        ('users', '0028_alter_album_spotify_id_alter_artist_spotify_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdStartTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SPOTIFY_GLOBAL', 'Spotify Global'), ('SPOTIFY_VIRAL', 'Spotify Viral'), ('LASTFM_GLOBAL', 'Lastfm Global')], max_length=32)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField(null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.track')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('track', 'source')},
            },
        ),
    ]
