# Generated by Django 5.2.7 on 2026-02-10 21:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('recomendations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('spotify', 'Spotify top items'), ('listening', 'Listening history'), ('lastfm', 'Last.fm'), ('computed', 'Computed aggregate')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_users', to='music.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weight'],
                'indexes': [models.Index(fields=['user', 'source', '-weight'], name='recomendati_user_id_32e845_idx'), models.Index(fields=['tag', '-weight'], name='recomendati_tag_id_f07556_idx')],
                'unique_together': {('user', 'tag', 'source')},
            },
        ),
    ]
