# Generated by Django 5.2.7 on 2026-02-02 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0003_coldstarttrack'),
        ('users', '0028_alter_album_spotify_id_alter_artist_spotify_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coldstarttrack',
            options={'ordering': ['source', 'rank']},
        ),
        migrations.AlterField(
            model_name='coldstarttrack',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time this entry was refreshed from the source'),
        ),
        migrations.AlterField(
            model_name='coldstarttrack',
            name='score',
            field=models.FloatField(blank=True, help_text='Optional normalized score used for ranking', null=True),
        ),
        migrations.AlterField(
            model_name='coldstarttrack',
            name='source',
            field=models.CharField(choices=[('SPOTIFY_GLOBAL', 'Spotify Global Top'), ('SPOTIFY_VIRAL', 'Spotify Viral'), ('LASTFM_GLOBAL', 'Last.fm Global Top')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='coldstarttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_start_entries', to='users.track'),
        ),
        migrations.AddIndex(
            model_name='coldstarttrack',
            index=models.Index(fields=['source', 'rank'], name='recomendati_source_c4bf9e_idx'),
        ),
        migrations.AddIndex(
            model_name='coldstarttrack',
            index=models.Index(fields=['track'], name='recomendati_track_i_387685_idx'),
        ),
    ]
