# Generated by Django 5.2.7 on 2026-02-05 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0004_alter_coldstarttrack_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LIKE', 'like'), ('SKIP', 'skip'), ('NOT_MY_STYLE', 'not my style')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cold_start_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_events', to='recomendations.coldstarttrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'cold_start_track'), name='unique_onboarding_event_per_track')],
            },
        ),
    ]
