# Generated by Django 5.2.7 on 2026-02-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_artist_name_alter_artist_popularity_and_more'),
        ('recomendations', '0004_recommendation_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendationitem',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='recommendationitem',
            index=models.Index(fields=['recommendation', 'rank'], name='rec_item_rec_rank_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('track__isnull', False)), fields=('recommendation', 'track'), name='unique_recommendation_track'),
        ),
        migrations.AddConstraint(
            model_name='recommendationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('artist__isnull', False)), fields=('recommendation', 'artist'), name='unique_recommendation_artist'),
        ),
    ]
