# Generated by Django 5.2.7 on 2026-02-16 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0005_alter_recommendationitem_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), ('SKIP', 'skip')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recomendations.recommendation')),
                ('recommendation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recomendations.recommendationitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='recfb_user_created_idx'), models.Index(fields=['recommendation', 'action'], name='recfb_rec_action_idx'), models.Index(fields=['recommendation_item'], name='recfb_item_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'recommendation_item'), name='uniq_user_rec_item_fb')],
            },
        ),
    ]
