# Generated by Django 5.2.7 on 2026-02-05 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0005_onboardingevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingevent',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='onboardingevent',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order in onboarding flow (1..N)', null=True),
        ),
        migrations.AlterField(
            model_name='onboardingevent',
            name='action',
            field=models.CharField(choices=[('LIKE', 'Like'), ('SKIP', 'Skip'), ('NOT_MY_STYLE', 'Not My Style')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='onboardingevent',
            index=models.Index(fields=['user', 'created_at'], name='recomendati_user_id_8805f1_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingevent',
            index=models.Index(fields=['user', 'action'], name='recomendati_user_id_d61bcb_idx'),
        ),
    ]
