# Generated by Django 5.2.7 on 2026-03-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0006_recommendationfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldstarttrack',
            name='source',
            field=models.CharField(choices=[('SPOTIFY_GLOBAL', 'Spotify Global Top'), ('SPOTIFY_VIRAL', 'Spotify Viral'), ('LASTFM_GLOBAL', 'Last.fm Global Top'), ('SPOTIFY_RELATED', 'Spotify Related Artists')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='source',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('spotify', 'Spotify top items'), ('listening', 'Listening history'), ('lastfm', 'Last.fm'), ('computed', 'Computed aggregate')], db_index=True, max_length=50),
        ),
    ]
